[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"
version_files = [
    "pyproject.toml:version",
    "src/orbittrack/__init__.py:__version__"
]
update_changelog_on_bump = true
major_version_zero = true
